# This script aims to answer the question: Are temperatures of one year significantly 
# correlated with the next year, across years in a given location? It does so by comparing the correlation coefficient of
# the given dataset to those of some randomly permuted datasets.
#
# ARGUMENTS
# None
#
# INPUT
# KeyWestAnnualMeanTemperatures.Rdata available at https://github.com/mhasoba/TheMulQuaBio/blob/master/content/data/KeyWestAnnualMeanTemperatures.Rdata
#
# OUTPUT
# approximate p-value 

rm(list= ls())

#load, examine and plot KeyWestAnnualMeanTemperatures.RData
data_set <- get(load("../Data/KeyWestAnnualMeanTemperatures.RData"))

ls.str(data_set) #display data_set

plot(data_set) 

#compute the correlation between successive years T [n-1] vs T[n]
corr_succ <- data.frame(data_set[,2][data_set[,1] -1], data_set[,2][data_set[,1]])
b <- unlist(cor(corr_succ, method="spearman")) [1,2] #unlist() creates a vector of correlation coefficient between successive years

# repeat it 10000 times randomly permuting the time series
# sample() can generate random permutation 

for(x in 1:10000){
    corr_succ<-sample(data_set[,2], length(data_set[,1]), replace = FALSE) #shuffle data 
    corr_succ<-data.frame(data_set[,2][data_set[,1] -1], data_set[,2][data_set[,1]])
    a <-unlist(cor(corr_succ, method="spearman")) [1,2] #Spearman correlation of new pairs generated by random permutation
}

#calculation of the p-value: fraction of new correlation coefficients (a) that are greater than b
length(a[which(a>b)])/length(a) #p-value of 0<- significant autocorrelation of temperature between years
